#!/bin/bash
PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

direct_copy_dot_files=(.tmux.conf .vim .vimrc .gitconfig git-completion.bash .bash_profile)
append_dot_files=(.bashrc )

green(){
  echo -e "\033[1;32m$1\033[0;00m";
}
red(){
  echo -e "\033[1;31m$1\033[0;00m";
}
add_link(){
  filename=$1
  targetpath=$2
  
  if [ -z "$targetpath" ]
    then
      target="$HOME/$filename"
      source="$PROJECT_DIR/$filename"
  else
    target="$targetpath/$filename"
    source="$PROJECT_DIR/$filename"
  fi

  if [ -L $target ] # is Symbolic link
    then
      green "  $filename already linked"
  elif [ -e $target ]
    then
      red "  $filename original"
  else
    ln -s $source $target
      green "  $filename added"
  fi
}

append_link_to_source(){
  target="$HOME/$1"
  source="$PROJECT_DIR/$1"
  file_linked=`grep -F "$source" $target`

  if [ ! -e $target ] # Add file and source
    then
      `touch $target`
      $(echo "source $source" >> $target)
      green "  $1 created and appended"
  elif [ "$file_linked" == '' ] # File exists and no link inside
    then
      $(echo "source $source" >> $target)
      green "  $1 appended"
  else
    green "  $1 already appended"
  fi
}

echo "  Linking"
echo "  -------"
if [ ! -d "~/.config" ] || [ ! -d "~/.config/nvim" ]; then
  `mkdir -p ~/.config/nvim/`
fi

add_link "init.vim" "$HOME/.config/nvim"

for dot_file in ${direct_copy_dot_files[*]}
do
  add_link $dot_file
done

echo "  Appending"
echo "  ---------"
for dot_file in ${append_dot_files[*]}
do
  append_link_to_source $dot_file
done

