#!/bin/bash
HOME=~
PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

dot_vim_target="$HOME/.vim"
vimrc_target="$HOME/.vimrc"

dot_vim="$PROJECT_DIR/.vim"
vimrc="$PROJECT_DIR/.vimrc"

dot_files=(.vim .vimrc .gitconfig)

add_dot_link(){
  target="$HOME/$1"
  source="$PROJECT_DIR/$1"

  if [ -L $target ]
    then
      echo "A dot-file version of $1 already exists."
  elif [ -e $target ]
    then
      echo "An original version of $1 exists."
  else
    ln -s $source $target
      echo "$1 added."
  fi
}

for dot_file in ${dot_files[*]}
do
  add_dot_link $dot_file
done




if [ ! -L $vimrc_target ]
  then
    ln -s $vimrc $vimrc_target
fi
